# Site settings
title: Bike theft maps
description: > #
  A live map of bike thefts from bikeindex.org thefts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://map.bikewise.org" # the base hostname & protocol for your site
twitter_username: bikeindex
github_username: sethherr
# Build settings
exclude:
  - README.markdown
  - CNAME
  - Gemfile
  - Gemfile.lock
# Plugins don't run on GitHub pages, so make sure that things work without this!
plugins:
  - jekyll-environment-variables